#!/usr/bin/env bash
# Configuring Ubuntu container’s Nginx installation to listening on port 80

sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
